# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install",
  "cd frontend && npm run build",
  "cd backend && npm run build"
]

[start]
cmd = "node backend/dist/index.js"