# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm run install:all"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "NODE_ENV=production npm run start:production"